#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.6~bpo9+1
if [ -x "/etc/init.d/subutai-nginx" ] && [ "$1" = remove ]; then
	invoke-rc.d subutai-nginx stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/11.1.6~bpo9+1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'subutai-nginx.service' >/dev/null || true
fi
# End automatically added section
